### ISSUE TITLE
Generic linked list implementation

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/wifire-os#18]
We need it badly, now. Two major requirements are:
* no memory allocation for list nodes (i.e. nodes are embedded into structures),
* any structure may be easily linked by several lists. 

There're a few solutions:
* [Linux Driver Development](http://www.makelinux.net/ldd3/) chapter 11.5.
* [FreeBSD queues](http://nxr.netbsd.org/xref/src-freebsd/sys/sys/queue.h)

Just choose bare minimum interface and present it as a header file, don't start implementation yet. I'd go for doubly linked circular list variant - it seems to be the most versatile.

**Comment by Killavus** [comment]
I just created the pull request being the first minimal step to implement this feature.

**Comment by cahirwpz** [comment]
We need those pesky lists now - please prepare a patch ASAP :)

**Comment by Killavus** [comment]
It'll be done today :)

**Comment by cahirwpz** [comment]
I'm still waiting...
